server:
  port: 8084

spring:
  application:
    name: notification-service

  mail:
    #https://support.google.com/accounts/answer/185833?hl=ru
    username: islam@gmail.com
    password: password
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"     # либо строго пакет common events
      spring.json.use.type.headers: false

app:
  kafka:
    topics:
      booking-created: booking-topic
  notification:
    max-attempts: 5


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
