services:
  # =============== INFRA ===============

  postgres:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks: [rbs-net]

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # MinIO Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio-data:/data
    networks: [ rbs-net ]

  # init: creates bucket and makes it public-read
  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      - minio
    networks: [ rbs-net ]
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin}; do
        echo 'waiting for minio...'; sleep 2;
      done &&
      mc mb -p local/${MINIO_BUCKET:-rbs-media} || true &&
      mc anonymous set download local/${MINIO_BUCKET:-rbs-media} &&
      echo 'MinIO bucket is ready: ${MINIO_BUCKET:-rbs-media} (public read)'
      "

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks: [rbs-net]

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - rbs-net
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
    volumes:
      - kafka_data:/var/lib/kafka/data

  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: eureka-server
    env_file: .env
    ports:
      - "8761:8761"
    networks: [rbs-net]
    depends_on:
      - postgres

  # =============== SERVICES ===============

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: user-service
    env_file: .env
    ports:
      - "8083:8083"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${PG_USER}
      DB_PASS: ${PG_PASS}

      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    networks: [rbs-net]
    depends_on:
      - eureka-server
      - postgres

  restaurant-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: restaurant-service
    env_file: .env
    ports:
      - "8081:8081"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${PG_USER}
      DB_PASS: ${PG_PASS}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      MINIO_ENDPOINT: http://minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_PUBLIC_BASE_URL: ${MINIO_PUBLIC_BASE_URL}
    networks: [rbs-net]
    depends_on:
      - eureka-server
      - postgres
      - redis
      - minio

  booking-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: booking-service
    env_file: .env
    ports:
      - "8082:8082"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${PG_USER}
      DB_PASS: ${PG_PASS}
    networks: [rbs-net]
    depends_on:
      - eureka-server
      - postgres

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: notification-service
    env_file: .env
    ports:
      - "8084:8084"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${PG_USER}
      DB_PASS: ${PG_PASS}
      KAFKA_BOOTSTRAP: ${KAFKA_BOOTSTRAP}
    networks: [rbs-net]
    depends_on:
      - eureka-server
      - postgres
      - kafka

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: api-gateway
    env_file: .env
    ports:
      - "8080:8080"
    networks: [rbs-net]
    depends_on:
      - eureka-server
      - user-service
      - restaurant-service
      - booking-service
      - notification-service

networks:
  rbs-net:
    driver: bridge

volumes:
  pg_data:
  minio-data:
  kafka_data:
