services:
  # =============== INFRA ===============

  postgres:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks: [rbs-net]

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks: [rbs-net]

  kafka:
    image: bitnami/kafka:3.7
    ports:
      - "9092:9092"
    networks: [rbs-net]
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_CLUSTER_ID}
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093

      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka

  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: eureka-server
    env_file: .env
    ports:
      - "8761:8761"
    networks: [rbs-net]
    depends_on:
      - postgres

  # =============== SERVICES ===============

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: user-service
    env_file: .env
    ports:
      - "8083:8083"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${PG_USER}
      DB_PASS: ${PG_PASS}
    networks: [rbs-net]
    depends_on:
      - eureka-server
      - postgres

  restaurant-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: restaurant-service
    env_file: .env
    ports:
      - "8081:8081"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${PG_USER}
      DB_PASS: ${PG_PASS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    networks: [rbs-net]
    depends_on:
      - eureka-server
      - postgres
      - redis

  booking-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: booking-service
    env_file: .env
    ports:
      - "8082:8082"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${PG_USER}
      DB_PASS: ${PG_PASS}
    networks: [rbs-net]
    depends_on:
      - eureka-server
      - postgres

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: notification-service
    env_file: .env
    ports:
      - "8084:8084"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${PG_USER}
      DB_PASS: ${PG_PASS}
      KAFKA_BOOTSTRAP: ${KAFKA_BOOTSTRAP}
    networks: [rbs-net]
    depends_on:
      - eureka-server
      - postgres
      - kafka

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: api-gateway
    env_file: .env
    ports:
      - "8080:8080"
    networks: [rbs-net]
    depends_on:
      - eureka-server
      - user-service
      - restaurant-service
      - booking-service
      - notification-service

networks:
  rbs-net:
    driver: bridge

volumes:
  pg_data:
  kafka_data:
