server:
  port: 8080

jwt:
  access-secret: ${JWT_SECRET}
  issuer: user-service

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        - id: user-auth-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**

        - id: user-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: restaurant-route
          uri: lb://restaurant-service
          predicates:
            - Path=/api/v1/restaurants/**

        - id: booking-route
          uri: lb://booking-service
          predicates:
            - Path=/api/v1/bookings/**

        - id: notification-route
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus