server:
  port: 8080

jwt:
  access-secret: ${JWT_SECRET}
  issuer: user-service

app:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN}

spring:
  application:
    name: api-gateway
  profiles:
    default: dev

  cloud:
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: maximumSize=1000,expireAfterWrite=30s
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        - id: user-auth-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**

        - id: user-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: restaurant-route
          uri: lb://restaurant-service
          predicates:
            - Path=/api/v1/restaurants/**

        - id: dish-photo-route
          uri: lb://restaurant-service
          predicates:
            - Path=/api/v1/dishes/**

        - id: booking-route
          uri: lb://booking-service
          predicates:
            - Path=/api/v1/bookings/**

        - id: notification-route
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

---

spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    my.project.apigateway: DEBUG
    org.springframework.security: INFO
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger{36} - %msg%n"

---

spring:
  config:
    activate:
      on-profile: test

logging:
  level:
    root: WARN
    my.project.apigateway: WARN
    org.springframework.security: WARN
    org.springframework.cloud.gateway: WARN
    reactor.netty.http.client: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger{36} - %msg%n"

---

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: INFO
    my.project.apigateway: INFO
    org.springframework.security: WARN
    org.springframework.cloud.gateway: WARN
    reactor.netty.http.client: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger{36} - %msg%n"