server:
  port: 0

jwt:
  access-secret: ${JWT_SECRET}
  issuer: user-service

spring:
  application:
    name: booking-service
  profiles:
    default: dev

  cloud:
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: maximumSize=1000,expireAfterWrite=30s

  datasource:
    url: jdbc:postgresql://${BOOKING_DB_HOST}:${BOOKING_DB_PORT}/bookingdb
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${MAX_POOL_SIZE:25}
      minimum-idle: ${MIN_IDLE:5}
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 1800000


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  kafka:
    topics:
      booking-created: booking-created-topic
      booking-cancelled: booking-cancelled-topic

pricing:
  offer-ttl-minutes: 10
  currency: RUB

  sigmoid:
    k: 8
    center: 0.5

  history:
    period-days: 90
    min-bookings-for-history: 50
    full-bookings-for-history: 150
    min-bookings-for-table-history: 50
    full-bookings-for-table-history: 150
    min-observations-for-calendar-class: 5
    full-observations-for-calendar-class: 20
    min-bookings-for-weight-history: 50
    full-bookings-for-weight-history: 150
    weight-update-rate: 0.1
    urgency-scale-hours: 24

  calendar:
    is-day-off-url: https://isdayoff.ru
    peak-holidays:
      - "2026-12-31"
      - "2026-02-14"
      - "2026-03-08"

  system-limits:
    min-pricing-charge: 0
    max-pricing-charge: 10000

  defaults:
    restaurant-min-pricing-charge: 100
    restaurant-max-pricing-charge: 1000
    weekday-demand: 0.5
    time-interval-demand: 0.5
    table-demand: 0.5
    neutral-calendar-context: 0.5

    weights:
      LOAD_BLOCK: 0.5
      HISTORICAL_DEMAND_BLOCK: 0.5
      CALENDAR_CONTEXT_BLOCK: 0.5
      OCCUPANCY_PARAMETER: 0.5
      URGENCY_PARAMETER: 0.5
      OCCUPANCY_URGENCY_INTERACTION: 0.5
      WEEKDAY_DEMAND_PARAMETER: 0.5
      TIME_INTERVAL_DEMAND_PARAMETER: 0.5
      TABLE_DEMAND_PARAMETER: 0.5

    calendar-coefficients:
      WORKDAY: 0.5
      WEEKEND: 0.5
      HOLIDAY: 0.5
      PEAK_HOLIDAY: 0.5

  scheduler:
    weights-update-cron: "0 0 3 * * *"
    calendar-sync-cron: "0 0 4 */14 * *"
    calendar-coefficients-update-cron: "0 20 3 * * *"
    history-snapshot-cron: "0 30 2 * * *"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    my.project.bookingservice: DEBUG
    org.springframework.security: INFO
    org.springframework.kafka: INFO
    org.hibernate.SQL: INFO
    org.springframework.cache: INFO
    org.springframework.data.redis: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger{36} - %msg%n"

---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    my.project.bookingservice: WARN
    org.springframework.security: WARN
    org.springframework.kafka: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.springframework.cache: WARN
    org.springframework.data.redis: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger{36} - %msg%n"

---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: INFO
    my.project.bookingservice: INFO
    org.springframework.security: WARN
    org.springframework.kafka: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.springframework.cache: WARN
    org.springframework.data.redis: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger{36} - %msg%n"