server:
  port: 8082

jwt:
  access-secret: ${JWT_SECRET}
  issuer: user-service

spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/bookingdb
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false


app:
  kafka:
    topics:
      booking-created: booking-created-topic
      booking-cancelled: booking-cancelled-topic

pricing:
  offer-ttl-minutes: 10
  currency: RUB

  sigmoid:
    k: 8
    center: 0.5

  history:
    period-days: 90
    min-bookings-for-history: 50
    full-bookings-for-history: 150
    min-bookings-for-table-history: 50
    full-bookings-for-table-history: 150
    min-observations-for-calendar-class: 5
    full-observations-for-calendar-class: 20
    min-bookings-for-weight-history: 50
    full-bookings-for-weight-history: 150
    weight-update-rate: 0.1
    urgency-scale-hours: 24

  calendar:
    is-day-off-url: https://isdayoff.ru
    country-code: ru
    holidays:
      - "2026-01-01"
      - "2026-01-02"
      - "2026-01-07"
      - "2026-02-23"
      - "2026-03-08"
      - "2026-05-01"
      - "2026-05-09"
      - "2026-06-12"
      - "2026-11-04"
    peak-holidays:
      - "2026-12-31"
      - "2026-02-14"
      - "2026-03-08"

  system-limits:
    min-pricing-charge: 0
    max-pricing-charge: 10000

  defaults:
    restaurant-min-pricing-charge: 100
    restaurant-max-pricing-charge: 1000
    weekday-demand: 0.5
    time-interval-demand: 0.5
    table-demand: 0.5
    neutral-calendar-context: 0.5

    weights:
      LOAD_BLOCK: 0.5
      HISTORICAL_DEMAND_BLOCK: 0.5
      CALENDAR_CONTEXT_BLOCK: 0.5
      OCCUPANCY_PARAMETER: 0.5
      URGENCY_PARAMETER: 0.5
      OCCUPANCY_URGENCY_INTERACTION: 0.5
      WEEKDAY_DEMAND_PARAMETER: 0.5
      TIME_INTERVAL_DEMAND_PARAMETER: 0.5
      TABLE_DEMAND_PARAMETER: 0.5

    calendar-coefficients:
      WORKDAY: 0.5
      WEEKEND: 0.5
      HOLIDAY: 0.5
      PEAK_HOLIDAY: 0.5

  scheduler:
    weights-update-cron: "0 0 3 * * *"
    calendar-coefficients-update-cron: "0 20 3 * * *"
    history-snapshot-cron: "0 30 2 * * *"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    root: INFO
    my.project.bookingservice: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
    org.apache.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger{36} - %msg%n"
