server:
  port: 8083

jwt:
  access-secret: ${JWT_SECRET:SSBkb24ndCB0YWtlIG1vbmV5IGZvciBteSBmbHlpbmcgYWJpbGl0eSwgYW5kIGV2ZW4gbW9yZSBzbyBmb3IgbXkgYmVhdXR5}
  refresh-secret: ${JWT_REFRESH_SECRET:VGhlcmUgaXMgbm8gc2VjcmV0IGluZ3JlZGllbnQuIDwuLi4+IFRvIG1ha2Ugc29tZXRoaW5nIHNwZWNpYWwsIHlvdSBqdXN0IGhhdmUgdG8gYmVsaWV2ZSB0aGF0IGl0IGlzIHNvbWV0aGluZyBzcGVjaWFsLg==}
  access-lifetime: 15m
  refresh-lifetime: 1d
  issuer: user-service

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/userdb
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus