server:
  port: 8083

jwt:
  access-secret: ${JWT_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  access-lifetime: 1h
  refresh-lifetime: 1d
  issuer: user-service

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/userdb
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus