package my.project.bookingservice.pricing.enums;

public enum PricingWeightCode {
	LOAD_BLOCK,
	HISTORICAL_DEMAND_BLOCK,
	CALENDAR_CONTEXT_BLOCK,

	OCCUPANCY_PARAMETER,
	URGENCY_PARAMETER,
	OCCUPANCY_URGENCY_INTERACTION,

	WEEKDAY_DEMAND_PARAMETER,
	TIME_INTERVAL_DEMAND_PARAMETER,
	TABLE_DEMAND_PARAMETER
}

