server:
  port: 8081

jwt:
  access-secret: ${JWT_SECRET}
  issuer: user-service

spring:
  application:
    name: restaurant-service


  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/restaurantdb
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "restaurant-service::"

minio:
  endpoint: ${MINIO_ENDPOINT}
  accessKey: ${MINIO_ROOT_USER}
  secretKey: ${MINIO_ROOT_PASSWORD}
  publicBaseUrl: ${MINIO_PUBLIC_BASE_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    root: INFO
    my.project.restaurantservice: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger{36} - %msg%n"
