server:
  port: 0

jwt:
  access-secret: ${JWT_SECRET}
  issuer: user-service

spring:
  application:
    name: restaurant-service
  profiles:
    default: dev

  cloud:
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: maximumSize=1000,expireAfterWrite=30s

  datasource:
    url: jdbc:postgresql://${RESTAURANT_DB_HOST}:${RESTAURANT_DB_PORT}/restaurantdb
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${MAX_POOL_SIZE:25}
      minimum-idle: ${MIN_IDLE:5}
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 1800000


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "restaurant-service::"

minio:
  endpoint: ${MINIO_ENDPOINT}
  accessKey: ${MINIO_ROOT_USER}
  secretKey: ${MINIO_ROOT_PASSWORD}
  publicBaseUrl: ${MINIO_PUBLIC_BASE_URL}

pricing:
  defaults:
    min-pricing-charge: 100
    max-pricing-charge: 1000
  system-limits:
    min-pricing-charge: 0
    max-pricing-charge: 10000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    my.project.restaurantservice: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
    org.springframework.cache: INFO
    org.springframework.data.redis: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger{36} - %msg%n"

---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    my.project.restaurantservice: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.springframework.cache: WARN
    org.springframework.data.redis: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger{36} - %msg%n"

---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: INFO
    my.project.restaurantservice: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.springframework.cache: WARN
    org.springframework.data.redis: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger{36} - %msg%n"